### ISSUE TITLE
Looking for Dummy data

### ISSUE THREAD

**Issue by NiloySarker** [Charitable/Charitable#311] opened 2017-03-12 21:51 UTC
Hi, I am planning to use the Charitable plugin for upcoming premium Theme.
Is it possible to give me the dummy content .xml file?
so it will save my time.
Regards,
Niloy

**Comment by ericnicolaas** [comment] 2017-03-15 23:38
Duplicate of https://wordpress.org/support/topic/looking-for-dummy-data/

**Closed by ericnicolaas** 2017-03-15 23:38 UTC
