### ISSUE TITLE
Clicking "Donate" Multiple Times Results in Multiple Donations

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#164] opened 2016-07-22 14:31 UTC
Hi @ericnicolaas,

Our team discovered a potentially serious issue with the donation form - if the user clicks the donate button multiple times, multiple donations are processed, charging the user's card each time.

The proposed solution is to hide the donate button when making the ajax request.

Additionally, if the server responds with a 500 when processing the donation (have seen this with an error from authorize.net), there is no error message and the spinner remains on the screen.  These two issues would have to be handled together.

I have @cyhtan, our JavaScript expert, working on a PR to fix.

**Comment by ericnicolaas** [comment] 2016-07-23 03:00
Ouch, that's a nasty one. Thanks for reporting @rafecolton and thanks for working on a fix @cyhtan. 

I've had a look at the fix. It looks like it's on the right track, but I would probably change the button to `disabled` instead of removing it altogether. I also wonder whether there's still a possibility of someone clicking on the button multiple times _really_ quickly before it is removed/disabled? Perhaps the start of the submit handler should set a `processing` flag, which is then removed when the AJAX request returns in the `done` handler.

**Comment by cyhtan** [comment] 2016-07-23 07:12
Hello @ericnicolaas! Happy to contribute. 

Personally, I think hiding the button provides a clearer UX: 

- The feedback that the button has been clicked is more prominent. If it is just disabled, there is no visual cue of what has happened unless we also restyle it. Even with a restyling, I would argue there's greater possibility of either missing the change (maybe it's under your finger on mobile, and the style change is not drastic enough) or misinterpreting the intent communicated by the style (maybe the user thinks the button is stuck in a mouse-over state and needs another press). Both of these potential issues vanish with the hiding approach.
- The location of the feedback is unmissable, occurring at the user's current focal point. Currently the spinner appears beneath the Donate button. It is quite possible to have the screen position in such a way that you miss the spinner's appearance entirely (see gif example).

![miss-spinner](https://cloud.githubusercontent.com/assets/12399087/17076234/8f1c81c4-507b-11e6-9365-3b0883cd02d4.gif)

In addition to missing the spinner, you probably noticed the page jump to a strange position. Below I have an example of the hide button behavior, as well as a fix for that I'd like to recommend. Currently, on successful submission of payment, two unnecessary and potentially confusing things happen: (1) the loading spinner is hidden and (2) the page scrolls to the top (which it normally does to display an error/notification response). Given that a successful response generates no messages, it is confusing for the user to be jumped briefly to the top of the page (which may still contain a previous error message). And with regards to the spinner, if that jump did not occur and the user were able to continue watching it, there would almost certainly be a moment of confusion in between when the AJAX completes, but the forthcoming redirect is still in process. If the redirect takes long, the user may navigate elsewhere or refresh out of confusion, and never be shown the redirect destination.

To address, of course, I propose not scrolling to the top if the request was successful, and **not** hiding the spinner at all, because the redirect is still in process, and it correctly cues them to continue waiting. Here is an example:

![hide-button](https://cloud.githubusercontent.com/assets/12399087/17076411/d95de522-507e-11e6-87c5-e9f0cab3e5c7.gif)

All that said, if you still feel strongly about not hiding the button, I'm happy to do as you've described and simply disable it. In either case, I think the `processing` flag you mention is an excellent idea, though I would put it in an `always` handler (`done` is only called on success, so a 500 would cause the flag to be stuck on, and block any subsequent attempts).

Lastly, (speaking of a 500) as @rafecolton mentioned, the client does not provide any user feedback or really handle 500s, just logging them to the console. I'd like to prepend an error to the form like the normal error behavior, with a message like `An error occurred during submission. Please try again. If the problem persists, please contact support.` What do you think?

Sorry for the lengthy post. Please share your thoughts on each of the issues above and I'll have a PR in shortly. Again, the proposals were: 

- Hiding donate button while spinner is visible
- On success, leaving spinner visible throughout redirect and removing the scroll-to-top behavior
- Handling 500s similar to other errors: hiding the spinner and displaying a message to the user 

Also, let me know if you'd like them to come from separate branches and PRs, or if all in the issue/164 branch is fine.

**Comment by ericnicolaas** [comment] 2016-07-23 09:33
Alright @cyhtan, you've argued your case very well. ;)

👍 to a PR against the `issue/164` branch (just created the branch). Let's just focus on these two things in this issue though:

- Hiding the donate button while the spinner is visible
- Keeping the spinner visible on a successful donation request

For the 500 issue, I suspect that that is specific to the Authorize.Net extension, so let's open an issue about that in the Bitbucket repo for that extension. Do you have a BB account I can invite to that repo?

**Comment by cyhtan** [comment] 2016-07-25 05:49
@ericnicolaas Thanks! :) 

I've just put the PR in for the issues discussed. 

I do think the 500 issue that @rafecolton brought up still needs addressing however. It may be that the Authorize.Net extension is causing the problem, but regardless of where problem is coming from, the client should probably be equipped to handle a failed server response (which may be happening now or in the future, for any number of reasons) in a way that doesn't confuse the user. Currently it just jumps to the top of the page with no error message displayed. I was proposing to communicate it just like the other form errors, using some sort of generalized error explanation. 

Do you have any better thoughts on how to approach a UX improvement here? I can open another issue for this if you like.

**Comment by ericnicolaas** [comment] 2016-07-25 05:54
Thanks for the PR @cyhtan. Looks like it's bundling in a very large backlog of commits though. Could you create a fresh PR that only includes the changes you've made? Easiest option for you is probably to create a fresh branch on your end, based on the current `master`, and then make your changes in that. 

I see your point re. the 500 error needing handling. I'm happy to have that opened as a separate issue here.

**Comment by cyhtan** [comment] 2016-07-25 06:23
Hey @ericnicolaas, I actually did base my branch on the current master. I think the issue is arising because I was making the PR to the issue/164 branch you created, but that branch appears to be ~500 commits behind master (last commit 2015). Let me know if I'm missing something, and how you'd like me to proceed. Would like to get the PR in today if possible.

**Comment by ericnicolaas** [comment] 2016-07-25 06:27
Ah, you're right. Sorry about that @cyhtan. Just recreated the branch based on current `master`.

**Comment by cyhtan** [comment] 2016-07-25 06:36
@ericnicolaas No worries :)

**Comment by ericnicolaas** [comment] 2016-07-25 06:37
Thanks for re-issuing that PR against the updated branch. I've merged it into the branch. Will do some basic testing and then merge into `master`.

**Comment by cyhtan** [comment] 2016-07-25 06:38
Great! Thanks for all the speedy responses.

**Closed** 2016-07-25 09:57 UTC
Labels: bug
