### ISSUE TITLE
Shortcode content appears in Gutenberg editor

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#661] opened 2019-03-13 14:25 UTC
In my page content I have the `[charitable_my_donations]` shortcode, and the output of the shortcode is visible in the background:

![image](https://user-images.githubusercontent.com/507025/54286311-f2cfa580-45e6-11e9-951b-7fb86ee1abd0.png)

The whole table is there, it's just under the toolbar, etc.

**Comment by ericnicolaas** [comment] 2019-10-03 04:55
@helgatheviking Never noticed this issue! I've just tried to reproduce, but no luck. You still getting this?

**Comment by ericnicolaas** [comment] 2020-10-29 01:39
I think this has cropped up again, but now with the [charitable_logout] shortcode. Can reproduce when the [charitable_logout] shortcode is on the page twice. 

Reopening for more investigation.

**Comment by ericnicolaas** [comment] 2020-12-17 05:27
The logout issue was related to #834. Fixed with 87fa4fe. 

I'm going to close this since I was never able to reproduce the original issue with the [charitable_my_donations] shortcode.

**Closed by ericnicolaas** 2020-12-17 05:27 UTC
Labels: could not reproduce
